apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: kubernetes-unir
  labels:
    app: mongodb
spec:
  clusterIP: None
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongodb

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: kubernetes-unir
  labels:
    app: mongodb
spec:
  replicas: 1
  serviceName: mongodb-svc
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.1.8-xenial
        envFrom:
        - configMapRef:
            name: mongodb-app-cm  
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
        - name: dbdata
          mountPath: /data/db
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
  volumeClaimTemplates:
  - metadata:
      name: dbdata
      labels:
        app: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-app-cm
  namespace: kubernetes-unir
data:
  MONGO_INITDB_ROOT_USERNAME: "sammy"
  MONGO_INITDB_ROOT_PASSWORD: "unir"