apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: applications
  labels:
    app: mongodb
spec:
  clusterIP: None
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongodb

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: applications
  labels:
    app: mongodb
spec:
  replicas: 1
  serviceName: mongodb-svc
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.14-focal
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
      labels:
        app: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi