apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  namespace: kubernetes-unir
  labels:
    app: node-app
spec:
  type: LoadBalancer
  ports:
  - port: 30000
    targetPort: 3000
    protocol: TCP
  selector:
    app: node-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: kubernetes-unir
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: app
        image: pedroeltorre/unir-contenedores:nodejs
        envFrom:
        - configMapRef:
            name: node-app-cm
        ports:
        - name: app
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 2
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-app-cm
  namespace: kubernetes-unir
data:
  MONGO_USERNAME: "sammy"
  MONGO_PASSWORD: "unir"
  MONGO_HOSTNAME: "mongodb-svc"
  MONGO_PORT: "27017"
  MONGO_DB: "sharkinfo"